### ISSUE TITLE
Can't resolve immer.

### ISSUE THREAD

**Issue by johanatan** [adamhwang/optioncharts.net#1]
![image](https://github.com/adamhwang/optioncharts.net/assets/583903/f1ea8376-2cfb-4635-8c28-449d5cfe7e96)

**Comment by adamhwang** [comment]
I'm going to need a little more info than an error message to help. Repro steps would help. An example would be better.

**Comment by johanatan** [comment]
The repro steps are in your readme. npm run dev if I recall.

I’ll give you my node and npm versions when I am back at my computer.

**Comment by adamhwang** [comment]
Did you run `npm install` before?

**Comment by johanatan** [comment]
Yep it succeeded

**Comment by adamhwang** [comment]
Glad to hear it!
